// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20230328023757_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.Property<string>("SeasonVisited")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("User_Name")
                        .HasColumnType("longtext");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            City = "San Francisco",
                            Country = "USA",
                            Rating = 4,
                            Review = "I love visiting the city in the spring",
                            SeasonVisited = "spring",
                            State = "California",
                            UserName = "Luckie"
                        },
                        new
                        {
                            PlaceId = 2,
                            City = "San Diego",
                            Country = "USA",
                            Rating = 5,
                            Review = "Gorgeous in the summer",
                            SeasonVisited = "summer",
                            State = "California",
                            UserName = "Luckie"
                        },
                        new
                        {
                            PlaceId = 3,
                            City = "Las Vegas",
                            Country = "USA",
                            Rating = 2,
                            Review = "I was not a fan of Vegas",
                            SeasonVisited = "summer",
                            State = "Nevada",
                            UserName = "Luckie"
                        },
                        new
                        {
                            PlaceId = 4,
                            City = "Grand Canyon Village",
                            Country = "USA",
                            Rating = 5,
                            Review = "Most beautiful place I've ever seen",
                            SeasonVisited = "summer",
                            State = "Arizona",
                            UserName = "Luckie"
                        },
                        new
                        {
                            PlaceId = 5,
                            City = "Cleveland",
                            Country = "USA",
                            Rating = 3,
                            Review = "City itself so-so, amazing people",
                            SeasonVisited = "winter",
                            State = "Ohio",
                            UserName = "Luckie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
